<?php
/**
 * Harta redirecturilor 301 de pe site-ul vechi (Shopify) catre cel nou.
 *
 * FISIER GENERAT de bin/redirects/build-map.php pe 2026-09-05 - nu se editeaza de mana.
 * Cheile sunt caile vechi normalizate (fara domeniu, fara prefixul de limba,
 * litere mici, fara slash final); valorile sunt caile noi pe limbi. Cand
 * lipseste varianta ruseasca, se foloseste cea romaneasca.
 *
 * @package Herbal_Therapy
 */

return array(
    'generated' => '2026-09-05',
    'fallback' => array(
        'shop' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        'home' => array('ro' => '/', 'ru' => '/ru/'),
        'blog' => array('ro' => '/blog/', 'ru' => '/ru/blog/'),
        'cart' => array('ro' => '/cos/', 'ru' => '/ru/cart/'),
        'account' => array('ro' => '/contul-meu/', 'ru' => '/ru/my-account/'),
        'terms' => array('ro' => '/termenii-si-conditiile/'),
    ),
    'paths' => array(
        '/blogs/dureri-reumatice-și-musculare' => array('ro' => '/blog/', 'ru' => '/ru/blog/'),
        '/blogs/dureri-reumatice-și-musculare/cele-mai-bune-vitamine-pentru-ameliorarea-durerilor-de-spate' => array('ro' => '/cele-mai-bune-vitamine-pentru-ameliorarea-durerilor-de-spate/', 'ru' => '/ru/luchshie-vitaminy-dlya-oblegcheniya-boli-v-spine/'),
        '/blogs/ingrijirea-tenului' => array('ro' => '/category/ingrijirea-tenului/', 'ru' => '/ru/category/uhod-za-kozhey-litsa/'),
        '/blogs/ingrijirea-tenului/cum-sa-tratezi-acnee-hormonala-sfaturi-și-soluții-eficiente' => array('ro' => '/cum-sa-tratezi-acnee-hormonala-sfaturi-si-solutii-eficiente/', 'ru' => '/ru/kak-lechit-gormonalnoe-akne-effektivnye-sovety-i-resheniya/'),
        '/blogs/news' => array('ro' => '/blog/', 'ru' => '/ru/blog/'),
        '/blogs/sfaturi-si-solutii-pentru-varice' => array('ro' => '/category/sfaturi-pentru-un-stil-de-viata-sanatos/', 'ru' => '/ru/category/sovety-dlya-zdorovogo-obraza-zhizni/'),
        '/blogs/sfaturi-si-solutii-pentru-varice/ingrijirea-naturala-de-vara-cu-herbal-therapy-produse-esențiale-pentru-sanatate-și-confort' => array('ro' => '/ingrijirea-naturala-de-vara-cu-herbal-therapy-produse-esentiale-pentru-sanatate-si-confort/', 'ru' => '/ru/naturalnyy-letniy-uhod-s-herbal-therapy-neobhodimye-produkty-dlya-zdorovya-i-komforta/'),
        '/blogs/vitamine-si-suplimente' => array('ro' => '/category/nutritie-si-suplimente/', 'ru' => '/ru/category/pitanie-i-dobavki/'),
        '/blogs/vitamine-si-suplimente/astenia-de-primavara' => array('ro' => '/cum-facem-fata-asteniei-de-primavara/', 'ru' => '/ru/kak-spravitsya-s-vesenney-asteniey/'),
        '/blogs/vitamine-si-suplimente/cum-sa-te-bucuri-de-mesele-imbelșugate-de-paște-fara-sa-iți-suprasoliciți-ficatul' => array('ro' => '/cum-sa-te-bucuri-de-mesele-imbelsugate-de-paste-fara-sa-iti-suprasoliciti-ficatul/', 'ru' => '/ru/kak-nasladitsya-obilnymi-paskhalnymi-zastolyami-ne-peregruzhaya-pechen/'),
        '/collections/all' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/collections/best-sellers' => array('ro' => '/produse/?orderby=popularity', 'ru' => '/ru/produkty/?orderby=popularity'),
        '/collections/colectie' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/collections/creme-unguente-și-loțiuni-1' => array('ro' => '/unguente/', 'ru' => '/ru/mazi/'),
        '/collections/oferte-speciale' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/collections/produse-copii' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/collections/produse-cosmetice' => array('ro' => '/cosmetica-medicala/', 'ru' => '/ru/meditsinskaya-kosmetika/'),
        '/collections/promotii' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/collections/siropuri-1' => array('ro' => '/siropuri/', 'ru' => '/ru/siropy/'),
        '/collections/toate-produsele' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/collections/uleiuri-cosmetice-1' => array('ro' => '/uleiuri/', 'ru' => '/ru/masla/'),
        '/collections/vitamine-și-minerale' => array('ro' => '/vitamine-si-suplimente/', 'ru' => '/ru/vitaminy-i-pishchevye-dobavki/'),
        '/collections/șampoane-geluri-de-duș-sapunuri' => array('ro' => '/produse/?cat=sampoane,geluri-de-dus,sapun-lichid', 'ru' => '/ru/produkty/?cat=shampuni,geli-dlya-dusha,zhidkoe-mylo'),
        '/pages/blog' => array('ro' => '/blog/', 'ru' => '/ru/blog/'),
        '/pages/catalog-pdf' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/pages/collection-bundles' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/pages/contact' => array('ro' => '/contact/', 'ru' => '/ru/kontakty/'),
        '/pages/despre-noi' => array('ro' => '/despre-noi/', 'ru' => '/ru/o-nas/'),
        '/pages/formular-returnare-produs' => array('ro' => '/termenii-si-conditiile/'),
        '/pages/intrebari-frecvente' => array('ro' => '/contact/', 'ru' => '/ru/kontakty/'),
        '/pages/modalitați-de-plata' => array('ro' => '/termenii-si-conditiile/'),
        '/pages/politica-cookie' => array('ro' => '/politica-de-confidentialitate/', 'ru' => '/ru/politika-konfidentsialnosti/'),
        '/pages/politica-de-confidentialitate' => array('ro' => '/politica-de-confidentialitate/', 'ru' => '/ru/politika-konfidentsialnosti/'),
        '/pages/politica-de-livrare-și-retur' => array('ro' => '/termenii-si-conditiile/'),
        '/pages/prelucrarea-datelor-cu-caracter-personal' => array('ro' => '/politica-de-confidentialitate/', 'ru' => '/ru/politika-konfidentsialnosti/'),
        '/pages/produse-copii' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/pages/program-de-fidelizare' => array('ro' => '/despre-noi/', 'ru' => '/ru/o-nas/'),
        '/pages/program-livrare-sarbatori' => array('ro' => '/contact/', 'ru' => '/ru/kontakty/'),
        '/pages/reviews' => array('ro' => '/', 'ru' => '/ru/'),
        '/pages/shared-wishlists' => array('ro' => '/favorite/', 'ru' => '/ru/izbrannoe/'),
        '/pages/termeni-și-condiții' => array('ro' => '/termenii-si-conditiile/'),
        '/pages/wishlist' => array('ro' => '/favorite/', 'ru' => '/ru/izbrannoe/'),
        '/policies/contact-information' => array('ro' => '/contact/', 'ru' => '/ru/kontakty/'),
        '/policies/privacy-policy' => array('ro' => '/politica-de-confidentialitate/', 'ru' => '/ru/politika-konfidentsialnosti/'),
        '/policies/refund-policy' => array('ro' => '/termenii-si-conditiile/'),
        '/policies/shipping-policy' => array('ro' => '/termenii-si-conditiile/'),
        '/policies/terms-of-service' => array('ro' => '/termenii-si-conditiile/'),
        '/products/apa-micelara-200ml' => array('ro' => '/apa-micelara-cu-hidrolat-de-lavanda-200-ml/', 'ru' => '/ru/micellyarnaya-voda-s-gidrolatom-lavandy-200-ml/'),
        '/products/apa-oxigenata-3' => array('ro' => '/apa-oxigenata-3-200-ml/', 'ru' => '/ru/perekis-vodoroda-3-200-ml/'),
        '/products/asigura-comanda-impotriva-furtului-sau-pierderii' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/products/balsam-buze-galbenele-propolis-aroma-capsuna-20ml' => array('ro' => '/balsam-de-buze-cu-galbenele-si-propolis-aroma-de-capsuna-20-ml/', 'ru' => '/ru/balzam-dlya-gub-s-kalenduloy-i-propolisom-s-aromatom-klubniki-20-ml/'),
        '/products/balsam-buze-musetel-aroma-pepene-galben-20ml' => array('ro' => '/balsam-de-buze-cu-musetel-aroma-de-pepene-galben-20-ml/', 'ru' => '/ru/balzam-dlya-gub-s-romashkoy-s-aromatom-dyni-20-ml/'),
        '/products/balsam-extracte-naturale-ulei-eucalipt-mentol-camfor-100ml' => array('ro' => '/balsam-cu-camfor-mentol-ulei-de-eucalipt-si-extracte-vegetale-naturale-100-ml/', 'ru' => '/ru/balzam-s-kamforoy-mentolom-maslom-evkalipta-i-naturalnymi-rastitelnymi-100-ml/'),
        '/products/bom-benghe-emulgel-75ml' => array('ro' => '/bom-benghe-emulgel-75-ml/', 'ru' => '/ru/bom-benghe-emulgel-75-ml/'),
        '/products/calciu-1000-mg-30-comprimate-herbal-therapy' => array('ro' => '/calciu-1000-mg-n30/', 'ru' => '/ru/kalciy-1000-mg-n30/'),
        '/products/calciu-1000-mg-60-comprimate-herbal-therapy' => array('ro' => '/calciu-1000-mg-n60/', 'ru' => '/ru/kalciy-1000-mg-n60/'),
        '/products/calciu-cu-vitamina-d3-aroma-de-caise-kids-x-30-cpr-calciu-250mg-sub-forma-de-carbonat-de-calciu-625-mg-vit-d3-cholecalciferol-5ug' => array('ro' => '/calciu-d3-cu-aroma-de-caise-n60/', 'ru' => '/ru/kalciy-d3-so-vkusom-abrikosa-n60/'),
        '/products/calciu-cu-vitamina-d3-cu-aroma-de-caise-herbal-therapy-60-tablete' => array('ro' => '/calciu-d3-cu-aroma-de-caise-n60/', 'ru' => '/ru/kalciy-d3-so-vkusom-abrikosa-n60/'),
        '/products/calciu-farmaco-gluconat-500mg-comprimate-masticabile' => array('ro' => '/calciu-farmacogluconat-500mg-n60/', 'ru' => '/ru/kalciy-farmako-glyukonat-500-mg-n60/'),
        '/products/calciu-magneziu-zinc-30-comprimate-herbal-therapy' => array('ro' => '/calciu-magneziu-zinc-n30/', 'ru' => '/ru/kalciy-magniy-cink-n30/'),
        '/products/calciu-magneziu-zinc-60-comprimate-herbal-therapy' => array('ro' => '/calciu-magneziu-zinc-n60/', 'ru' => '/ru/kalciy-magniy-cink-n60/'),
        '/products/calciu-magneziu-zinc-vitamina-d3-30-comprimate' => array('ro' => '/calciu-magneziu-zinc-vitamina-d3-n30/', 'ru' => '/ru/kalciy-magniy-cink-vitamin-d3-n30/'),
        '/products/calciu-magneziu-zinc-vitamina-d3-60-comprimate-herbal-therapy' => array('ro' => '/calciu-magneziu-zinc-vitamina-d3-n60/', 'ru' => '/ru/kalciy-magniy-cink-vitamin-d3-n60/'),
        '/products/calciu-vitamina-d3-forte-60-comprimate' => array('ro' => '/calciu-d3-forte-cu-aroma-de-portocala-n60/', 'ru' => '/ru/kalciy-d3-forte-so-vkusom-apelsina-n60/'),
        '/products/calciu-vitamina-d3-forte-aroma-portocala-x30-cpr-calciu-elementar-500mg-62-5-nr-vitamina-d3-colecalciferol-5ug-100-vnr' => array('ro' => '/calciu-d3-forte-cu-aroma-de-portocala-n60/', 'ru' => '/ru/kalciy-d3-forte-so-vkusom-apelsina-n60/'),
        '/products/crema-corp-hidratanta-niacinamida-parfum-floral-250ml' => array('ro' => '/crema-de-corp-hidratanta-cu-niacinamidab3-uleiuri-si-extracte-herbal-cu-parfum-floral-250-ml/', 'ru' => '/ru/uvlazhnyayuschiy-krem-dlya-tela-s-niacinamidom-b3-maslami-i-travyanymi-250-ml/'),
        '/products/crema-de-calcaie-cu-30-uree-100-ml' => array('ro' => '/crema-pentru-calcaie-crapate-30-uree-cu-extract-din-plante-100-ml/', 'ru' => '/ru/krem-dlya-potreskavsheysya-kozhi-pyatok-30-mocheviny-s-rastitelnym-100-ml/'),
        '/products/crema-de-corp-hidratanta-d-panthenol-și-parfum-pepene-galben-250-ml' => array('ro' => '/crema-de-corp-hidratanta-cu-d-panthenol-uleiuri-si-extracte-herbal-cu-parfum-de-pepene-galben-250ml/', 'ru' => '/ru/uvlazhnyayuschiy-krem-dlya-tela-s-d-pantenolom-maslami-i-travyanymi-250-ml/'),
        '/products/crema-de-maini-cu-extract-de-aloe-vera-și-ulei-de-struguri-50-ml' => array('ro' => '/crema-de-maini-cu-extract-de-aloe-vera-si-ulei-de-strugure-50-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktom-aloe-vera-i-maslom-vinogradnyh-kostochek-50-ml/'),
        '/products/crema-de-maini-cu-extract-de-catina-și-ulei-de-cocos-50-ml' => array('ro' => '/crema-de-maini-cu-extract-de-catina-si-ulei-de-cocos-50-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktom-oblepihi-i-kokosovym-maslom-50-ml/'),
        '/products/crema-de-maini-cu-extract-de-galbenele-și-ulei-de-masline-50-ml' => array('ro' => '/crema-de-maini-cu-extract-de-galbenele-si-ulei-de-masline-50-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktom-kalenduly-i-olivkovym-maslom-50-ml/'),
        '/products/crema-de-maini-cu-extract-de-immortelle-și-ulei-de-canepa-50-ml' => array('ro' => '/crema-de-maini-cu-extract-de-immortelle-si-ulei-de-canepa-50-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktom-bessmertnika-i-konoplyanym-maslom-50-ml/'),
        '/products/crema-de-maini-cu-extract-de-mușețel-și-ulei-de-migdale-50-ml' => array('ro' => '/crema-de-maini-cu-extract-de-musetel-si-ulei-de-migdale-50-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktom-romashki-i-mindalnym-maslom-50-ml/'),
        '/products/crema-de-maini-cu-extracte-de-galbenele-și-immortelle-și-ulei-de-masline-100-ml-herbal-therapy' => array('ro' => '/crema-de-maini-cu-galbenele-immortelle-si-ulei-de-masline-100-ml/', 'ru' => '/ru/krem-dlya-ruk-s-ekstraktami-kalenduly-bessmertnika-i-olivkovym-maslom-100-ml/'),
        '/products/crema-emulgel-artix-herbal-100ml' => array('ro' => '/artix-herbal-crema-emulgel-100-ml/', 'ru' => '/ru/artix-herbal-krem-emulgel-100-ml/'),
        '/products/crema-emulgel-reumix-herbal-100ml' => array('ro' => '/reumix-herbal-crema-emulgel-100-ml/', 'ru' => '/ru/reumix-herbal-krem-emulgel-100-ml/'),
        '/products/crema-emulgel-varix-herbal-100ml' => array('ro' => '/varix-herbal-crema-emulgel-100-ml/', 'ru' => '/ru/varix-herbal-krem-emulgel-100-ml/'),
        '/products/crema-geucamen-30ml' => array('ro' => '/geucamen-crema-30-ml/', 'ru' => '/ru/geucamen-krem-30-ml/'),
        '/products/crema-melkfett-extract-galbenele-vitamina-e-250ml' => array('ro' => '/melkfett-crema-cu-extract-de-galbenele-si-vitamina-e-250-ml/', 'ru' => '/ru/melkfett-krem-s-ekstraktom-kalenduly-i-vitaminom-e-250-ml/'),
        '/products/crom-picolinat-200-µg-30-capsule' => array('ro' => '/vitamine-si-suplimente/', 'ru' => '/ru/vitaminy-i-pishchevye-dobavki/'),
        '/products/dexpanthen-herbal-plus-emulgel-100ml' => array('ro' => '/dexpanthen-plus-herbal-vitamina-a-si-e-emulgel-100-ml/', 'ru' => '/ru/dexpanthen-plus-herbal-vitaminy-a-i-e-emulgel-100-ml/'),
        '/products/dexpanthen-plus-cu-vitamina-a-și-e-herbal-therapy-crema-tub-30-g' => array('ro' => '/dexpanthen-plus-vitamina-a-si-e-crema-30-g/', 'ru' => '/ru/dexpanthen-plus-vitaminy-a-i-e-krem-30-g/'),
        '/products/emulgel-artix-crema-pentru-articulații-și-dureri-musculare-300-ml' => array('ro' => '/artix-herbal-crema-emulgel-300-ml/', 'ru' => '/ru/artix-herbal-krem-emulgel-300-ml/'),
        '/products/emulgel-geucamen-75ml' => array('ro' => '/geucamen-emulgel-75-ml/', 'ru' => '/ru/geucamen-emulgel-75-ml/'),
        '/products/emulgel-varix-crema-impotriva-varicelor-și-a-picioarelor-obosite-300-ml' => array('ro' => '/varix-herbal-crema-emulgel-300-ml/', 'ru' => '/ru/varix-herbal-krem-emulgel-300-ml/'),
        '/products/flusept-cu-propolis-și-miere-n10-comprimate-orosolubile' => array('ro' => '/flusept-cu-propolis-si-miere-n10/', 'ru' => '/ru/flusept-s-propolisom-i-medom-n10/'),
        '/products/flusept-cu-salvie-și-eucalipt-n10-comprimate-orosolubile' => array('ro' => '/flusept-cu-salvie-si-eucalipt-n10/', 'ru' => '/ru/flusept-s-shalfeem-i-evkaliptom-n10/'),
        '/products/gel-de-dus-cu-eucalipt-salvie-și-ulei-de-canepa-herbal-therapy-500-ml' => array('ro' => '/gel-de-dus-cu-extract-de-salvie-ulei-de-eucalipt-si-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktom-shalfeya-maslom-evkalipta-i-konoplyanym-500-ml/'),
        '/products/gel-de-dus-cu-extract-de-catina-și-ulei-de-canepa-herbal-therapy-500-ml' => array('ro' => '/gel-de-dus-cu-extract-de-catina-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktom-oblepihi-konoplyanoe-maslo-500-ml/'),
        '/products/gel-de-dus-cu-extract-de-galbenele-coada-șoricelului-și-ulei-de-canepa-herbal-therapy-500-ml' => array('ro' => '/gel-de-dus-cu-extract-de-galbenele-si-coada-soricelului-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktami-kalenduly-i-tysyachelistnika-konoplyanoe-500-ml/'),
        '/products/gel-de-dus-cu-extract-de-immortelle-și-ulei-de-canepa-herbal-therapy-500-ml' => array('ro' => '/gel-de-dus-cu-extract-de-immortelle-si-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktom-bessmertnika-i-konoplyanym-maslom-500-ml/'),
        '/products/gel-de-dus-cu-extracte-naturale-herbal-și-ulei-de-canepa-herbal-therapy-500-ml' => array('ro' => '/gel-de-dus-cu-extracte-herbal-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktami-herbal-konoplyanoe-maslo-500-ml/'),
        '/products/gel-de-duș-cu-extract-de-mușețel-și-aloe-vera-ulei-de-canepa-500-ml' => array('ro' => '/gel-de-dus-cu-extract-de-musetel-si-aloe-vera-ulei-de-canepa-500-ml/', 'ru' => '/ru/gel-dlya-dusha-s-ekstraktami-romashki-i-aloe-vera-konoplyanoe-maslo-500-ml/'),
        '/products/ginkgo-biloba-80-mg-90-tab' => array('ro' => '/ginkgo-biloba-80-mg-n90/', 'ru' => '/ru/ginkgo-biloba-80-mg-n90/'),
        '/products/hepatoliv-silimarina-forte-140-mg-30-capsule' => array('ro' => '/hepatoliv-silimarina-forte-140-mg-n30/', 'ru' => '/ru/hepatoliv-silimarin-forte-140-mg-kapsuly-n30/'),
        '/products/loțiune-antiacneica-acid-salicilic-galbenele-levanțica-100ml' => array('ro' => '/acid-salicilic-1-cu-extract-de-galbenele-si-ulei-de-levantica-lotiune-antiacneica-100-ml/', 'ru' => '/ru/salicilovaya-kislota-1-s-ekstraktom-kalenduly-i-maslom-lavandy-loson-100-ml/'),
        '/products/loțiune-antiacneica-fața-corp-100ml' => array('ro' => '/lotiune-antiacneica-pentru-fata-si-corp-100-ml/', 'ru' => '/ru/loson-protiv-akne-dlya-lica-i-tela-100-ml/'),
        '/products/loțiune-demachianta-herbal-therapy-200-ml' => array('ro' => '/lotiune-demachianta-cu-extracte-herbal-naturale-200-ml/', 'ru' => '/ru/loson-dlya-snyatiya-makiyazha-s-naturalnymi-ekstraktami-herbal-200-ml/'),
        '/products/magneziu-vitamina-b6-30-capsule' => array('ro' => '/magneziu-vitamina-b6-capsule-n30/', 'ru' => '/ru/magniy-vitamin-b6-kapsuly-n30/'),
        '/products/melatonina-3-mg-30-comprimate' => array('ro' => '/melatonina-3mg-n30/', 'ru' => '/ru/melatonin-3-mg-n30/'),
        '/products/multivitamine-minerale-12-30-comprimate' => array('ro' => '/multivitamine-minerale-adolescenti-12-n30/', 'ru' => '/ru/multivitaminy-mineraly-dlya-podrostkov-12-n30/'),
        '/products/multivitamine-minerale-12-60-comprimate-herbal-therapy' => array('ro' => '/multivitamine-minerale-adolescenti-12-ani-n60/', 'ru' => '/ru/multivitaminy-mineraly-dlya-podrostkov-12-let-n60/'),
        '/products/multivitamine-minerale-adulti-30-comprimate-herbal-therapy' => array('ro' => '/multivitamine-minerale-adulti-n30/', 'ru' => '/ru/multivitaminy-mineraly-dlya-vzroslyh-n30/'),
        '/products/multivitamine-minerale-adulti-60-comprimate-herbal-therapy' => array('ro' => '/multivitamine-minerale-adulti-n60/', 'ru' => '/ru/multivitaminy-mineraly-dlya-vzroslyh-n60/'),
        '/products/pachet-pentru-bunici-imunitate-si-sanatate-pentru-sarbatori-linistite' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-bunici-ingrijire-pentru-picioare-grele' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-bunici-pentru-mușchi-și-articulații' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-bunici-sarbatori-fara-dureri-cu-remedii-naturale' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-ea-cadoul-perfect-pentru-piele-sanatoasa' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-ea-pentru-un-ten-sanatos' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-pentru-mamici-sarbatori-linistite-cu-ingrijire-completa-pentru-cei-mici' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-promotionaltoner-facial-si-balsam-de-buze-cu-musetel' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-promoțional-8-martie' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-unisex-ingrijire-completa-pentru-ten-acneic' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-unisex-pentru-ingrijire-completa-curațare-hidratare' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pachet-unisex-pentru-sanatate-bunastare-energie-claritate-relaxare' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pentru-ea-pachet-hidratant-regenerant' => array('ro' => '/reduceri/', 'ru' => '/ru/skidki/'),
        '/products/pickup-in-store' => array('ro' => '/produse/', 'ru' => '/ru/produkty/'),
        '/products/pudra-antitranspirație-herbal-therapy-50-g' => array('ro' => '/pudra-antitranspiratie-p-u-ingrijirea-pielii-corpului-50-g/', 'ru' => '/ru/pudra-antiperspirant-dlya-uhoda-za-kozhey-tela-50-g/'),
        '/products/pudra-mentolata-herbal-therapy-50-g' => array('ro' => '/pudra-mentolata-1-50g/', 'ru' => '/ru/mentolovaya-pudra-1-50-g/'),
        '/products/pudra-pentru-copii-cu-lavanda-și-vitamina-e-herbal-therapy-50-g' => array('ro' => '/pudra-pentru-copii-cu-lavanda-si-vitamina-e-50-g/', 'ru' => '/ru/detskaya-pudra-s-lavandoy-i-vitaminom-e-50-g/'),
        '/products/reliefix-soluție-calmanta-de-uz-extern-100-ml' => array('ro' => '/reliefix-solutie-calmanta-de-uz-extern-100-ml/', 'ru' => '/ru/reliefix-uspokaivayuschiy-rastvor-dlya-naruzhnogo-primeneniya-100-ml/'),
        '/products/reumix-emulgel-crema-impotriva-durerilor-reumatice-și-de-spate-300-ml' => array('ro' => '/reumix-herbal-crema-emulgel-300-ml/', 'ru' => '/ru/reumix-herbal-krem-emulgel-300-ml/'),
        '/products/sapun-lichid-cu-extract-de-aloe-vera-și-uleiuri-naturale-herbal-therapy-500-ml' => array('ro' => '/sapun-lichid-cu-extract-de-aloe-vera-si-uleiuri-naturale-500-ml/', 'ru' => '/ru/zhidkoe-mylo-s-ekstraktom-aloe-vera-i-naturalnymi-maslami-500-ml/'),
        '/products/sapun-lichid-cu-extract-de-ceai-verde-herbal-therapy-500-ml' => array('ro' => '/sapun-lichid-cu-extract-de-ceai-verde-si-uleiuri-naturale-500-ml/', 'ru' => '/ru/zhidkoe-mylo-s-ekstraktom-zelenogo-chaya-i-naturalnymi-maslami-500-ml/'),
        '/products/sapun-lichid-cu-extract-de-galbenele-și-uleiuri-naturale-herbal-therapy-500-ml' => array('ro' => '/sapun-lichid-cu-extract-de-galbenele-si-uleiuri-naturale-500-ml/', 'ru' => '/ru/zhidkoe-mylo-s-ekstraktom-kalenduly-i-naturalnymi-maslami-500-ml/'),
        '/products/sapun-lichid-cu-extract-de-mușețel-și-uleiuri-naturale-herbal-therapy-500-ml' => array('ro' => '/sapun-lichid-cu-extract-de-musetel-si-uleiuri-naturale-500-ml/', 'ru' => '/ru/zhidkoe-mylo-s-ekstraktom-romashki-i-naturalnymi-maslami-500-ml/'),
        '/products/sapun-lichid-cu-extract-herbal-și-uleiuri-naturale-herbal-therapy-500-ml' => array('ro' => '/sapun-lichid-cu-extracte-herbal-si-uleiuri-naturale-500-ml/', 'ru' => '/ru/zhidkoe-mylo-s-ekstraktami-herbal-i-naturalnymi-maslami-500-ml/'),
        '/products/seleniu-l-selenometionina-200-µg-30-capsule' => array('ro' => '/seleniu-l-selenometionina-200-%c2%b5g-30-capsule/', 'ru' => '/ru/selen-l-selenometionin-200-mkg-30-kapsul/'),
        '/products/sirop-imuno-cimbrișor-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-cimbrisor-200-ml/', 'ru' => '/ru/sirop-imuno-timyan-200-ml/'),
        '/products/sirop-imuno-detox-herbal-therapy-200-ml' => array('ro' => '/sirop-imuno-detox-200-ml/', 'ru' => '/ru/sirop-imuno-detox-200-ml/'),
        '/products/sirop-imuno-echinacea-patlagina-și-ghimbir-vitamina-c-200-ml' => array('ro' => '/sirop-imuno-echinaceea-patlagina-ghimbir-si-vitamina-c-200-ml/', 'ru' => '/ru/sirop-imuno-ehinaceya-podorozhnik-imbir-i-vitamin-c-200-ml/'),
        '/products/sirop-imuno-echinacea-zn-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-echinacea-zinc-200-ml/', 'ru' => '/ru/sirop-imuno-ehinaceya-cink-200-ml/'),
        '/products/sirop-imuno-hepatic-herbal-therapy-200-ml' => array('ro' => '/sirop-imuno-hepatic-200-ml/', 'ru' => '/ru/sirop-imuno-hepatic-200-ml/'),
        '/products/sirop-imuno-herbal-lax-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-herbal-lax-200-ml/', 'ru' => '/ru/sirop-imuno-herbal-lax-200-ml/'),
        '/products/sirop-imuno-iedera-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-iedera-200-ml/', 'ru' => '/ru/sirop-imuno-plyusch-200-ml/'),
        '/products/sirop-imuno-lemn-dulce-și-menta-200-ml-herbal-therapy' => array('ro' => '/siropuri/', 'ru' => '/ru/siropy/'),
        '/products/sirop-imuno-patlagina-vitamina-c-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-patlagina-vitamina-c-200-ml/', 'ru' => '/ru/sirop-imuno-podorozhnik-vitamin-c-200-ml/'),
        '/products/sirop-imuno-resveratrol-herbal-therapy-200-ml' => array('ro' => '/sirop-imuno-resveratrol-200-ml/', 'ru' => '/ru/sirop-imuno-resveratrol-200-ml/'),
        '/products/sirop-imuno-tusin-herbal-therapy-200-ml' => array('ro' => '/sirop-imuno-tusin-200-ml/', 'ru' => '/ru/sirop-imuno-tusin-200-ml/'),
        '/products/sirop-imuno-vitamine-copii-200-ml-herbal-therapy' => array('ro' => '/sirop-imuno-vitamine-copii-200-ml/', 'ru' => '/ru/sirop-imuno-vitaminy-dlya-detey-200-ml/'),
        '/products/sirop-pentru-imunitate-și-vitalitate-extract-de-maceșe-200-ml' => array('ro' => '/sirop-de-macese-200-ml/', 'ru' => '/ru/sirop-iz-shipovnika-200-ml/'),
        '/products/sirop-phytocalm-copii-200-ml-herbal-therapy' => array('ro' => '/sirop-phytocalm-copii-200-ml/', 'ru' => '/ru/sirop-phytocalm-dlya-detey-200-ml/'),
        '/products/sirop-phytocalm-somn-200-ml-herbal-therapy' => array('ro' => '/sirop-phytocalm-somn-200-ml/', 'ru' => '/ru/sirop-phytocalm-son-200-ml/'),
        '/products/spray-de-corp-cu-parfum-floral-lacramioara-și-iasomie-alba-herbal-therapy-120-ml' => array('ro' => '/spray-de-corp-hidratant-cu-parfum-floral-120-ml/', 'ru' => '/ru/uvlazhnyayuschiy-sprey-dlya-tela-s-cvetochnym-aromatom-120-ml/'),
        '/products/spumant-de-baie-detoxifiant-cu-extracte-herbal-1000-ml' => array('ro' => '/spumant-de-baie-detoxifiant-cu-extracte-din-plante-1000-ml/', 'ru' => '/ru/pena-dlya-vanny-detoksificiruyuschaya-s-rastitelnymi-ekstraktami-1000-ml/'),
        '/products/spumant-de-baie-relaxant-cu-extracte-din-plante-1000-ml' => array('ro' => '/spumant-de-baie-relaxant-cu-extracte-din-plante-1000-ml/', 'ru' => '/ru/pena-dlya-vanny-rasslablyayuschaya-s-rastitelnymi-ekstraktami-1000-ml/'),
        '/products/spumant-de-baie-revitalizant-cu-extracte-din-plante-1000-ml' => array('ro' => '/spumant-de-baie-revitalizant-cu-extracte-din-plante-1000-ml/', 'ru' => '/ru/pena-dlya-vanny-vosstanavlivayuschaya-s-rastitelnymi-ekstraktami-1000-ml/'),
        '/products/toner-facial-cu-extracte-herbal-niacinamida-b3-și-vitamina-e-herbal-therapy-100-ml' => array('ro' => '/toner-facial-cu-extracte-herbal-naturale-100-ml/', 'ru' => '/ru/tonik-dlya-lica-s-naturalnymi-ekstraktami-herbal-100-ml/'),
        '/products/ulei-camforat-herbal-therapy-200-ml' => array('ro' => '/uleiuri/', 'ru' => '/ru/masla/'),
        '/products/ulei-de-corp-cu-3-uleiuri-naturale-parfum-de-lapte-și-miere-200-ml' => array('ro' => '/ulei-de-corp-cu-3-uleiuri-naturale-parfum-de-lapte-si-miere-200-ml/', 'ru' => '/ru/maslo-dlya-tela-s-3-naturalnymi-maslami-s-aromatom-moloka-i-meda-200-ml/'),
        '/products/ulei-de-corp-revulsiv-herbal-therapy-500-ml' => array('ro' => '/ulei-de-corp-revulsiv-500-ml/', 'ru' => '/ru/maslo-dlya-tela-revulsiv-500-ml/'),
        '/products/ulei-de-magneziu-imbogațit-cu-extracte-din-plante-1000-ml' => array('ro' => '/ulei-de-magneziu-imbogatit-cu-extracte-din-plante-1000-ml/', 'ru' => '/ru/magnievoe-maslo-obogaschennoe-rastitelnymi-ekstraktami-1000-ml/'),
        '/products/ulei-de-parafina-herbal-therapy-100-ml' => array('ro' => '/uleiuri/', 'ru' => '/ru/masla/'),
        '/products/ulei-de-ricin-55-ml' => array('ro' => '/ulei-de-ricin-55-ml-herbal-therapy/', 'ru' => '/ru/kastorovoe-maslo-55-ml-herbal-therapy/'),
        '/products/ulei-de-ricin-herbal-therapy' => array('ro' => '/ulei-de-ricin-100-ml-herbal-therapy/', 'ru' => '/ru/kastorovoe-maslo-100-ml-herbal-therapy/'),
        '/products/ulei-de-vaselina-25-g' => array('ro' => '/ulei-de-vaselina-25-g/', 'ru' => '/ru/vazelinovoe-maslo-25-g/'),
        '/products/unguent-ardei-iute-20ml' => array('ro' => '/unguent-cu-capsicum-ardei-iute-20-ml/', 'ru' => '/ru/maz-s-kapsikumom-ostryy-perec-20-ml/'),
        '/products/unguent-cu-aloe-vera-și-mușețel-cocos-lavanda-vitamina-e-herbal-therapy-40-ml' => array('ro' => '/unguent-cu-musetel-si-aloe-vera-40-ml/', 'ru' => '/ru/maz-s-romashkoy-i-aloe-vera-40-ml/'),
        '/products/unguent-cu-capsicum-ardei-iute-ameliorarea-durerilor-musculare-și-incalzire-rapida-50-ml' => array('ro' => '/unguent-cu-capsicum-ardei-iute-50-ml/', 'ru' => '/ru/maz-s-kapsikumom-ostryy-perec-50-ml/'),
        '/products/unguent-cu-catina-herbal-therapy-20-ml' => array('ro' => '/unguent-cu-ulei-de-catina-20-ml/', 'ru' => '/ru/maz-s-oblepihovym-maslom-20-ml/'),
        '/products/unguent-cu-extract-de-aloe-vera-20ml' => array('ro' => '/unguent-cu-aloe-vera-50-ml/', 'ru' => '/ru/maz-s-aloe-vera-50-ml/'),
        '/products/unguent-cu-extract-de-aloe-vera-regenerare-și-vindecare-a-ranilor-și-taieturilor-minore-20-ml' => array('ro' => '/unguent-cu-aloe-vera-20-ml/', 'ru' => '/ru/maz-s-aloe-vera-20-ml/'),
        '/products/unguent-cu-extract-de-arnica-50-ml' => array('ro' => '/unguent-cu-arnica-50-ml/', 'ru' => '/ru/maz-s-arnikoy-50-ml/'),
        '/products/unguent-cu-extract-de-arnica-ameliorarea-vanatailor-și-contuziilor-20-ml' => array('ro' => '/unguent-cu-arnica-20-ml/', 'ru' => '/ru/maz-s-arnikoy-20-ml/'),
        '/products/unguent-cu-extract-de-catina' => array('ro' => '/unguent-cu-ulei-de-catina-50-ml/', 'ru' => '/ru/maz-s-oblepihovym-maslom-50-ml/'),
        '/products/unguent-cu-extract-de-galbenele' => array('ro' => '/unguent-cu-galbenele-50-ml/', 'ru' => '/ru/maz-s-kalenduloy-50-ml/'),
        '/products/unguent-cu-extract-de-musetel' => array('ro' => '/unguent-cu-musetel-50-ml/', 'ru' => '/ru/maz-s-romashkoy-50-ml/'),
        '/products/unguent-cu-extract-de-mușețel-20ml' => array('ro' => '/unguent-cu-musetel-20-ml/', 'ru' => '/ru/maz-s-romashkoy-20-ml/'),
        '/products/unguent-cu-extract-de-rostopasca' => array('ro' => '/unguent-cu-rostopasca-50-ml/', 'ru' => '/ru/maz-s-chistotelom-50-ml/'),
        '/products/unguent-cu-extract-de-rostopasca-20ml' => array('ro' => '/unguent-cu-rostopasca-20-ml/', 'ru' => '/ru/maz-s-chistotelom-20-ml/'),
        '/products/unguent-cu-extract-de-siminoc' => array('ro' => '/unguent-cu-siminoc-50-ml/', 'ru' => '/ru/maz-s-bessmertnikom-50-ml/'),
        '/products/unguent-cu-extract-de-siminoc-20ml' => array('ro' => '/unguent-cu-siminoc-20-ml/', 'ru' => '/ru/maz-s-bessmertnikom-20-ml/'),
        '/products/unguent-cu-galbenele-cocos-lavanda-vitamina-e-herbal-therapy-40-ml' => array('ro' => '/unguent-cu-galbenele-40-ml/', 'ru' => '/ru/maz-s-kalenduloy-40-ml/'),
        '/products/unguent-cu-galbenele-herbal-therapy-20-ml' => array('ro' => '/unguent-cu-galbenele-20-ml/', 'ru' => '/ru/maz-s-kalenduloy-20-ml/'),
        '/products/unguent-cu-galbenele-si-propolis' => array('ro' => '/unguent-cu-galbenele-si-propolis-50-ml/', 'ru' => '/ru/maz-s-kalenduloy-i-propolisom-50-ml/'),
        '/products/unguent-cu-galbenele-și-propolis-cocos-lavanda-vitamina-e-herbal-therapy-40-ml' => array('ro' => '/unguent-cu-galbenele-si-propolis-40-ml/', 'ru' => '/ru/maz-s-kalenduloy-i-propolisom-40-ml/'),
        '/products/unguent-cu-galbenele-și-propolis-herbal-therpay-20-ml' => array('ro' => '/unguent-cu-galbenele-si-propolis-20-ml/', 'ru' => '/ru/maz-s-kalenduloy-i-propolisom-20-ml/'),
        '/products/unguent-cu-galbenele-și-siminoc-cocos-lavanda-vitamina-e-herbal-therapy-40-ml' => array('ro' => '/unguent-cu-galbenele-si-siminoc-40-ml/', 'ru' => '/ru/maz-s-kalenduloy-i-bessmertnikom-40-ml/'),
        '/products/unguent-cu-radacina-de-brusture' => array('ro' => '/unguent-cu-radacina-de-brusture-20-ml/', 'ru' => '/ru/maz-s-kornem-lopuha-20-ml/'),
        '/products/unguent-cu-radacina-de-brusture-efect-reparator-pentru-psoriazis-și-furuncule-50-ml' => array('ro' => '/unguent-cu-radacina-de-brusture-50-ml/', 'ru' => '/ru/maz-s-kornem-lopuha-50-ml/'),
        '/products/unguent-cu-radacina-de-gheara-diavolului' => array('ro' => '/unguent-cu-gheara-diavolului-50-ml/', 'ru' => '/ru/maz-s-dyavolskim-kogtem-50-ml/'),
        '/products/unguent-cu-radacina-de-gheara-diavolului-antiinflamator-muscular-și-articular-20-ml' => array('ro' => '/unguent-cu-gheara-diavolului-20-ml/', 'ru' => '/ru/maz-s-dyavolskim-kogtem-20-ml/'),
        '/products/unguent-cu-radacina-de-spanz' => array('ro' => '/unguent-cu-radacina-de-spanz-20-ml/', 'ru' => '/ru/maz-s-kornem-moroznika-20-ml/'),
        '/products/unguent-cu-radacina-de-spanz-ameliorarea-durerilor-de-spate-și-tensiunii-musculare-50-ml' => array('ro' => '/unguent-cu-radacina-de-spanz-20-ml/', 'ru' => '/ru/maz-s-kornem-moroznika-20-ml/'),
        '/products/unguent-cu-radacina-de-tataneasa-20-ml' => array('ro' => '/unguent-cu-radacina-de-tataneasa-20-ml/', 'ru' => '/ru/maz-s-kornem-okopnika-20-ml/'),
        '/products/unguent-cu-radacina-de-tataneasa-regenerare-rapida-vanatai-și-entorse-50-ml' => array('ro' => '/unguent-cu-radacina-de-tataneasa-20-ml/', 'ru' => '/ru/maz-s-kornem-okopnika-20-ml/'),
        '/products/unguent-cu-rostopasca-cocos-lavanda-vitamina-e-herbal-therapy-40-ml' => array('ro' => '/unguent-cu-rostopasca-40-ml/', 'ru' => '/ru/maz-s-chistotelom-40-ml/'),
        '/products/unguent-cu-ulei-de-canepa-și-immortelle-herbal-therapy-50-ml' => array('ro' => '/unguent-cu-ulei-de-canepa-si-immortelle-50-ml/', 'ru' => '/ru/maz-s-konoplyanym-maslom-i-bessmertnikom-50-ml/'),
        '/products/unguent-echinaceea-și-ceai-verde-herbal-therapy-50-ml' => array('ro' => '/unguent-cu-echinaceea-si-ceai-verde-50-ml/', 'ru' => '/ru/maz-s-ehinaceey-i-zelenym-chaem-50-ml/'),
        '/products/unguent-melissa-și-immortelle-herbal-therapy-50-ml' => array('ro' => '/unguent-cu-melissa-si-immortelle-50-ml/', 'ru' => '/ru/maz-s-melissoy-i-bessmertnikom-50-ml/'),
        '/products/unguent-salvie-și-eucalipt-herbal-therapy-50-ml' => array('ro' => '/unguent-cu-salvie-si-eucalipt-50-ml/', 'ru' => '/ru/maz-s-shalfeem-i-evkaliptom-50-ml/'),
        '/products/vaselina-cosmetica-floral-herbal-therapy-50-ml' => array('ro' => '/vaselina-floral-50-ml/', 'ru' => '/ru/vazelin-floral-50-ml/'),
        '/products/vaselina-cosmetica-herbal-therapy-100-ml' => array('ro' => '/vaselina-cosmetica-100-ml/', 'ru' => '/ru/vazelin-kosmeticheskiy-100-ml/'),
        '/products/vaselina-cosmetica-rose-herbal-therapy-50-ml' => array('ro' => '/vaselina-rose-50-ml/', 'ru' => '/ru/vazelin-rose-50-ml/'),
        '/products/vitamina-a-10-000-ui-30-capsule' => array('ro' => '/vitamine-si-suplimente/', 'ru' => '/ru/vitaminy-i-pishchevye-dobavki/'),
        '/products/vitamina-b-complex-c-30-capsule' => array('ro' => '/b-complex-vitamina-c-n30/', 'ru' => '/ru/b-complex-vitamin-c-kapsuly-n30/'),
        '/products/vitamina-c-100-mg-cu-glucoza-herbal-therapy-120-tablete' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-n120/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-n120/'),
        '/products/vitamina-c-100-mg-cu-glucoza-n10-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-n10/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-n10/'),
        '/products/vitamina-c-100-mg-cu-glucoza-și-lamaie-herbal-therapy-120-tablete' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-si-aroma-de-lamaie-n120/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-i-vkusom-limona-n120/'),
        '/products/vitamina-c-100-mg-cu-glucoza-și-portocala-herbal-therapy-120-tablete' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-si-aroma-de-portocala-n120/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-i-vkusom-apelsina-n120/'),
        '/products/vitamina-c-100-mg-cu-glucoza-și-strugure-herbal-therapy-120-tablete' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-si-aroma-de-struguri-n120/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-i-vkusom-vinograda-n120/'),
        '/products/vitamina-c-100-mg-cu-glucoza-și-zmeura-herbal-therapy-120-tablete' => array('ro' => '/vitamina-c-100-mg-cu-glucoza-si-aroma-de-zmeura-n120/', 'ru' => '/ru/vitamin-c-100-mg-s-glyukozoy-i-vkusom-maliny-n120/'),
        '/products/vitamina-c-100-mg-cu-propolis-echinaceea-și-zinc-60-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-propolis-echinacea-si-zinc-n60/', 'ru' => '/ru/vitamin-c-100-mg-s-propolisom-ehinaceey-i-cinkom-n60/'),
        '/products/vitamina-c-100-mg-cu-propolis-herbal-therapy-60-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-cu-propolis-n60/', 'ru' => '/ru/vitamin-c-100-mg-s-propolisom-n60/'),
        '/products/vitamina-c-100-mg-cu-propolis-și-echinaceea-herbal-therapy-60-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-propolis-si-echinacea-n60/', 'ru' => '/ru/vitamin-c-100-mg-propolis-i-ehinaceya-n60/'),
        '/products/vitamina-c-100-mg-cu-propolis-și-miere-herbal-therapy-60-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-cu-propolis-si-miere-n60/', 'ru' => '/ru/vitamin-c-100-mg-s-propolisom-i-medom-n60/'),
        '/products/vitamina-c-100-mg-cu-propolis-și-polen-herbal-therapy-60-comprimate-masticabile' => array('ro' => '/vitamina-c-100-mg-propolis-si-polen-n60/', 'ru' => '/ru/vitamin-c-100-mg-s-propolisom-i-pylcoy-n60/'),
        '/products/vitamina-c-1000-mg-cu-flavonoide-din-flori-de-soc-n30' => array('ro' => '/vitamina-c-1000-mg-cu-flavonoide-din-flori-de-soc-n30/', 'ru' => '/ru/vitamin-c-1000-mg-s-flavonoidami-cvetkov-buziny-n30/'),
        '/products/vitamina-c-300-mg-zinc-30-comprimate-herbal-therapy' => array('ro' => '/vitamina-c-300-mg-zinc-n30/', 'ru' => '/ru/vitamin-c-300-mg-cink-n30/'),
        '/products/vitamina-c-300-mg-zinc-60-comprimate-herbal-therapy' => array('ro' => '/vitamina-c-300-mg-zinc-n60/', 'ru' => '/ru/vitamin-c-300-mg-cink-n60/'),
        '/products/vitamina-c-500-mg-30-comprimate-herbal-therapy' => array('ro' => '/vitamina-c-500-mg-n30/', 'ru' => '/ru/vitamin-c-500-mg-n30/'),
        '/products/vitamina-c-500-mg-herbal-therapy-60-comprimate-masticabile' => array('ro' => '/vitamina-c-500-mg-n60/', 'ru' => '/ru/vitamin-c-500-mg-n60/'),
        '/products/vitamina-d3-2000-ui-herbal-therapy-30-comprimate' => array('ro' => '/vitamina-d3-2000ui-n30/', 'ru' => '/ru/vitamin-d3-2000-me-n30/'),
        '/products/vitamina-d3-4000-ui-herbal-therapy-30-comprimate' => array('ro' => '/vitamina-d3-4000ui-n30/', 'ru' => '/ru/vitamin-d3-4000-me-n30/'),
        '/products/zinc-picolinat-25-mg-30-capsule' => array('ro' => '/vitamine-si-suplimente/', 'ru' => '/ru/vitaminy-i-pishchevye-dobavki/'),
        '/products/șampon-cu-extract-de-aloe-vera-si-ulei-de-eucalipt-500-ml' => array('ro' => '/sampoane/', 'ru' => '/ru/shampuni/'),
        '/products/șampon-cu-extract-de-catina-și-ulei-de-canepa-herbal-therapy-300-ml' => array('ro' => '/sampon-cu-extract-de-catina-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktom-oblepihi-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-cu-extract-de-galbenele-și-coada-șoricelului-ulei-de-canepa-herbal-therapy-100-ml' => array('ro' => '/sampon-cu-extracte-de-galbenele-si-coada-soricelului-ulei-de-canepa-100-ml/', 'ru' => '/ru/shampun-s-ekstraktami-kalenduly-i-tysyachelistnika-konoplyanoe-maslo-100-ml/'),
        '/products/șampon-cu-extract-de-salvie-ulei-de-eucalipt-și-ulei-de-canepa-herbal-therapy-300-ml' => array('ro' => '/sampon-cu-extracte-de-salvie-ulei-de-eucalipt-si-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktom-shalfeya-maslom-evkalipta-i-konoplyanym-maslom-300-ml/'),
        '/products/șampon-cu-extract-de-urzica-500-ml' => array('ro' => '/sampon-cu-extracte-de-urzica-si-immortelle-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktami-krapivy-i-bessmertnika-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-cu-extract-de-urzica-și-immortelle-ulei-de-canepa-herbal-therapy-100-ml-1' => array('ro' => '/sampon-cu-extracte-de-urzica-si-immortelle-ulei-de-canepa-100-ml/', 'ru' => '/ru/shampun-s-ekstraktami-krapivy-i-bessmertnika-konoplyanoe-maslo-100-ml/'),
        '/products/șampon-cu-extracte-herbal-și-ulei-de-canepa-herbal-therapy-300-ml' => array('ro' => '/sampon-cu-extracte-herbal-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktami-herbal-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-cu-galbenele-coada-șoricelului-și-ulei-de-canepa-herbal-therapy-300-ml' => array('ro' => '/sampon-cu-extracte-de-galbenele-si-coada-soricelului-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktami-kalenduly-i-tysyachelistnika-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-cu-ulei-de-eucalipt-și-extract-de-salvie-ulei-de-canepa-herbal-therapy-100-ml' => array('ro' => '/sampon-cu-extracte-de-salvie-ulei-de-eucalipt-si-ulei-de-canepa-100-ml/', 'ru' => '/ru/shampun-s-ekstraktom-shalfeya-maslom-evkalipta-i-konoplyanym-maslom-100-ml/'),
        '/products/șampon-cu-urzica-immortelle-și-ulei-de-canepa-herbal-therapy-300-ml' => array('ro' => '/sampon-cu-extracte-de-urzica-si-immortelle-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktami-krapivy-i-bessmertnika-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-prevenire-caderea-parului-extract-de-musetel-si-aloe-vera-300-ml' => array('ro' => '/sampon-cu-extracte-de-musetel-si-aloe-vera-ulei-de-canepa-300-ml/', 'ru' => '/ru/shampun-s-ekstraktami-romashki-i-aloe-vera-konoplyanoe-maslo-300-ml/'),
        '/products/șampon-stimuleaza-creșterea-parului-extract-de-salvie-ulei-de-eucalipt-și-ulei-de-canepa-1000-ml' => array('ro' => '/sampon-cu-extracte-de-salvie-ulei-de-eucalipt-si-ulei-de-canepa-1000-ml/', 'ru' => '/ru/shampun-s-ekstraktom-shalfeya-maslom-evkalipta-i-konoplyanym-maslom-1000-ml/'),
        '/products/🎁-cadou-gel-de-dus-catifelare-și-hidratare-extract-de-immortelle-și-ulei-de-canepa-500-ml' => array('ro' => '/geluri-de-dus/', 'ru' => '/ru/geli-dlya-dusha/'),
        '/products/🎁-cadou-sapun-lichid-catifelare-și-hidratare-extract-de-mușețel-și-uleiuri-naturale-500-ml' => array('ro' => '/sapun-lichid/', 'ru' => '/ru/zhidkoe-mylo/'),
    ),
);
